name: ${project.name}
version: ${project.version}
main: com.lenis0012.bukkit.marriage2.internal.MarriagePlugin
author: lenis0012
description: A plugin which provides the function to start a relationship in minecraft.
website: https://www.spigotmc.org/resources/marriage-reloaded-1-15-1-8.18998/
softdepend: [Vault, PlotSquared]
api-version: '1.16'
manifest-url: ${updater.manifestUrl}
commands:
  marry:
    description: Marriage main command.
    usage: /marry <args>
permissions:
  marry.default:
    description: Allows access to marriage player commands
    default: true